### PR TITLE
Changed all scene and script file names be consistent.

### LINKED ISSUE #44: Consistent File Names
Currently the file names across our resources are of various types. We have

PascalCase
With Spaces
With_Underscores
lowercase

We need to pick some sort of consistent file naming scheme.

### PR DESCRIPTION
**Pull request by wDvy**
All scene file names are written With_Underscores (first always caps with spaces as underscores).

All script file names are written in camelCase. (the first word has no caps, then all other words' first letters are capitalized)

also removed some parts of file names that included 'test' that are part of the active build of the game right now. not the scripts tho :/

surprisingly painless only a few bugs when changing names, want to make sure it runs well on everyone else's builds too.

### CODE REVIEW

**Comment by CollinDewey** [comment]
You missed a few

Also why not rename all the assets as well?

**Comment by wDvy** [comment]
Which ones did I miss? 🧍‍♂️ other than gun.tscn planning on deleting that one.

Also not really as worried about the assets, they're pretty distinguishable from one another

**Review by EJ-S — CHANGES_REQUESTED** [review]
This broke everything on my machine talking about missing dependencies and then I can't launch the game. If we push this we should show people how to fix these issues.

**Comment by CollinDewey** [comment]
Are you sure you staged all of the renames? Also what's the point in having a naming system if the assets are immune to the naming scheme?

I also feel like it's a bit strange to have scenes use underscores but scripts in camelCase.

**Comment by wDvy** [comment]
I'll probably table these changes until the next meeting, I'm interested to see what those dependency issues are. 

Also, all of the names (excluding the assets lol) are correct on my godot client collin, not sure which ones are showing up incorrectly for you. Are you pulling it to the godot client or just looking at file changes on GitHub? please list which files are incorrect so I can check them out xx

**Comment by wDvy** [comment]
> I also feel like it's a bit strange to have scenes use underscores but scripts in camelCase.

yeah I'll prob change everything to With_Underscores, thought it would be good to differentiate but godot names scripts after the scene its being attached to so it would annoying to keep up with after a while.

**Pull request closed without merging**
