### PR TITLE
Changed all filenames to be With_Underscores

### LINKED ISSUE #44: Consistent File Names
Currently the file names across our resources are of various types. We have

PascalCase
With Spaces
With_Underscores
lowercase

We need to pick some sort of consistent file naming scheme.

### PR DESCRIPTION
**Pull request by CollinDewey**
Let's give issue #44 another go. This is an alternative PR intended to replace #51.

Lmk if everything works as intended

### CODE REVIEW

**Comment by CollinDewey** [comment]
I hope it goes without saying, but please Squash and Merge and not just merge.

**Comment by wDvy** [comment]
lol glad you said that I would have just merged lol still learning GitHub. Looks good though! 😎 some older files in there that we can definitely get rid of but we'll get that another time.

**Review by wDvy — APPROVED** [review]

**Review by EJ-S — APPROVED** [review]
this work on my machine well, I think this will work

**Comment by CollinDewey** [comment]
> some older files in there that we can definitely get rid of but we'll get that another time.

Yeah I kinda figured I'd just rename everything in place for now and another PR should be made for cleanup in that regard

**Pull request merged**
