### PR TITLE
Added Death Screen when player dies

### LINKED ISSUE #42: Death Screen
Would like to have a death screen so the game doesn't crash when we die :/

Should have a button UI element to reset the scene and a nice label letting us know we died.

### PR DESCRIPTION
**Pull request by wDvy**
Lets player know they died and gives a button to reset scene.

### CODE REVIEW

**Comment by wDvy** [comment]
pretty innocuous addition but should save us some time with testing, make sure it works on yours 👍

**Comment by CollinDewey** [comment]
Rebased

**Comment by CollinDewey** [comment]
This screen looks a little goofy on my ultrawide, but so does most of the game, to be fair.

image

**Comment by wDvy** [comment]
yeah does look goofy should be an easy fix after the camera stuff is done lol

**Pull request merged**
