### PR TITLE
Reset collision layers

### LINKED ISSUE #38: fix player shooting himself

### PR DESCRIPTION
**Pull request by wDvy**
Added new setlayers() function for all enemies and player.

### CODE REVIEW

**Comment by CollinDewey** [comment]
Wouldn't it make sense to just create an enum that can be used instead of making people need to refer to a collision wiki page?

**Review by EJ-S — CHANGES_REQUESTED** [review]
I'm with Collin on this one I like the idea of a set layers function but we should also make an ENUM to not have to check the wiki when we want to set collision layers

**Comment by wDvy** [comment]
> I'm with Collin on this one I like the idea of a set layers function but we should also make an ENUM to not have to check the wiki when we want to set collision layers

good idea

**Review by CollinDewey — COMMENTED** [review]
Noticed there was a space in the new file Scenes/Global Variables.tscn. Turns out this isn't the only case of weird naming. Created issue #44 so we could discuss this. I just dislike spaces in file names.

**Pull request merged**
